<?php
// Local/production overrides for configuration
// Update SITE_URL to your live domain so emails use correct absolute links.
// Example: https://rcnmissionhospital.org

// Auto-generated by Admin Settings on 2025-11-11T18:42:42+00:00
define('PAYPAL_BUSINESS_EMAIL','info@rcnmissionhospital.org');
define('PAYPAL_RETURN_URL','/thank-you');
define('PAYPAL_CANCEL_URL','/partners');
define('PAYPAL_HOSTED_BUTTON_ID','');
define('PAYPAL_USE_SANDBOX',false);
define('PAYSTACK_PUBLIC_KEY','');
define('PAYSTACK_SECRET_KEY','');
define('PAYSTACK_PLAN_CODE_NGN_MONTHLY','');
define('PAYSTACK_CALLBACK_URL','');
define('SMTP_HOST','smtp.gmail.com');
define('SMTP_PORT',587);
define('SMTP_USER','grccglobal@gmail.com');
define('SMTP_PASS','oggp bncq ohea vect');
define('CONTACT_RECIPIENT','');
define('QUEUE_PAUSE_SENDING',false);
define('QUEUE_MAX_ATTEMPTS_NEWSLETTER',5);
define('QUEUE_MAX_ATTEMPTS_NEWSLETTER_TEST',5);
define('QUEUE_MAX_ATTEMPTS_CONTACT',5);
define('LOG_MAX_BYTES',2097152);
define('LOG_MAX_FILES',5);
define('SITE_URL', 'https://rcnmh.org');
