<?php
// Application constants and configuration values

// Optional local override file generated by Admin Settings
// If present, it may pre-define constants, which we will not redefine below
if (file_exists(__DIR__ . '/config.local.php')) {
    require_once __DIR__ . '/config.local.php';
}

if (!defined('APP_NAME')) define('APP_NAME', 'RCN Mission Hospital');

// // Database configuration (update for production)
// if (!defined('DB_HOST')) define('DB_HOST', 'localhost');
// if (!defined('DB_NAME')) define('DB_NAME', 'u572560474_rcn');
// if (!defined('DB_USER')) define('DB_USER', 'u572560474_rcn');
// if (!defined('DB_PASS')) define('DB_PASS', 'Noah@grcc25');
// Database configuration (update for production)
if (!defined('DB_HOST')) define('DB_HOST', 'localhost');
if (!defined('DB_NAME')) define('DB_NAME', 'rcn_mission_hospital');
if (!defined('DB_USER')) define('DB_USER', 'root');
if (!defined('DB_PASS')) define('DB_PASS', '');

// SMTP / PHPMailer
if (!defined('SMTP_HOST')) define('SMTP_HOST', 'smtp.zoho.com');
if (!defined('SMTP_PORT')) define('SMTP_PORT', 587);
if (!defined('SMTP_USER')) define('SMTP_USER', ''); // your Zoho email
// Dedicated recipient for contact form messages (optional). If empty, falls back to SMTP_USER.
if (!defined('CONTACT_RECIPIENT')) define('CONTACT_RECIPIENT', '');
if (!defined('SMTP_PASS')) define('SMTP_PASS', ''); // your Zoho app password
// Allow configuring whether SMTP authentication is required
if (!defined('SMTP_AUTH')) define('SMTP_AUTH', true);
// Configure SMTP encryption: 'tls' (default), 'ssl', or 'none'
if (!defined('SMTP_SECURE')) define('SMTP_SECURE', 'tls');

// reCAPTCHA v3 (optional)
if (!defined('RECAPTCHA_SITE_KEY')) define('RECAPTCHA_SITE_KEY', '6LcNXAgsAAAAAJhKhDomIxEc5jK3-MpAFDKYd8AC');
if (!defined('RECAPTCHA_SECRET_KEY')) define('RECAPTCHA_SECRET_KEY', '6LcNXAgsAAAAAP9wojC9rEzjRoiPwUHsRERhKSme');

// TinyMCE (WYSIWYG Editor)
if (!defined('TINYMCE_API_KEY')) define('TINYMCE_API_KEY', 'yvut7vepk3ovqga8taovrtp9ntup09d9cl4udjh35o02uuqk');

// Security/Session settings
if (!defined('SESSION_TIMEOUT')) define('SESSION_TIMEOUT', 1800); // 30 minutes
if (!defined('LOGIN_MAX_ATTEMPTS')) define('LOGIN_MAX_ATTEMPTS', 10);
if (!defined('LOGIN_LOCK_WINDOW')) define('LOGIN_LOCK_WINDOW', 900); // 15 minutes

// Uploads
if (!defined('UPLOAD_DIR')) define('UPLOAD_DIR', __DIR__ . '/../uploads/');
if (!defined('MAX_UPLOAD_BYTES')) define('MAX_UPLOAD_BYTES', 5 * 1024 * 1024); // 5MB

// Logging
// Rotate logs when they exceed this size (bytes). Overridable via includes/config.local.php.
if (!defined('LOG_MAX_BYTES')) define('LOG_MAX_BYTES', 2 * 1024 * 1024); // 2MB
// Keep at most this many rotated files per log (app.log.1 .. app.log.N)
if (!defined('LOG_MAX_FILES')) define('LOG_MAX_FILES', 5);

// Branding colors (used in Tailwind config and inline styles)
if (!defined('COLOR_MIDNIGHT_NAVY')) define('COLOR_MIDNIGHT_NAVY', '#0A1A3B');
if (!defined('COLOR_MISSION_ORANGE')) define('COLOR_MISSION_ORANGE', '#E36414');
if (!defined('COLOR_DEEP_RED')) define('COLOR_DEEP_RED', '#A32020');
if (!defined('COLOR_FLAME_RED')) define('COLOR_FLAME_RED', '#D9381E');
if (!defined('COLOR_WARM_ORANGE')) define('COLOR_WARM_ORANGE', '#F47A1F');
if (!defined('COLOR_SOFT_GRAY')) define('COLOR_SOFT_GRAY', '#F2F2F2');
if (!defined('COLOR_WHITE')) define('COLOR_WHITE', '#FFFFFF');

// Gradient CSS value per spec
if (!defined('RCN_GRADIENT')) define('RCN_GRADIENT', 'linear-gradient(135deg, #A32020, #D9381E 35%, #E36414 70%, #F47A1F)');

// Dynamic base path for subdirectory deployments (e.g., /rcnmissionhospital/ on WAMP)
$docRoot = isset($_SERVER['DOCUMENT_ROOT']) ? realpath($_SERVER['DOCUMENT_ROOT']) : null;
$appRoot = realpath(__DIR__ . '/..');
$base = '/';
if ($docRoot && $appRoot && strpos($appRoot, $docRoot) === 0) {
    $relative = str_replace('\\', '/', substr($appRoot, strlen($docRoot)));
    $relative = '/' . trim($relative, '/');
    $base = ($relative === '/' ? '/' : $relative . '/');
}
if (!defined('BASE_PATH')) define('BASE_PATH', $base);

// Base site URL for absolute links in emails and external callbacks
// Prefer environment variable to avoid CLI/server context issues
if (!defined('SITE_URL') && getenv('SITE_URL')) {
    $envUrl = trim(getenv('SITE_URL'));
    if ($envUrl !== '') {
        // Normalize: no trailing slash
        if (substr($envUrl, -1) === '/') {
            $envUrl = rtrim($envUrl, '/');
        }
        define('SITE_URL', $envUrl);
    }
}

// Payments - configure before going live
// Paystack
if (!defined('PAYSTACK_PUBLIC_KEY')) define('PAYSTACK_PUBLIC_KEY', '');
if (!defined('PAYSTACK_SECRET_KEY')) define('PAYSTACK_SECRET_KEY', '');
// Optional: set a Paystack Plan code for monthly recurring NGN donations
if (!defined('PAYSTACK_PLAN_CODE_NGN_MONTHLY')) define('PAYSTACK_PLAN_CODE_NGN_MONTHLY', '');
// Callback URL Paystack will redirect to after payment (must be HTTPS in production)
if (!defined('PAYSTACK_CALLBACK_URL')) define('PAYSTACK_CALLBACK_URL', '');

// PayPal
// Business email used for classic subscription form (Webscr). Alternatively set API credentials if using Checkout APIs.
if (!defined('PAYPAL_BUSINESS_EMAIL')) define('PAYPAL_BUSINESS_EMAIL', 'info@rcnmissionhospital.org');
// Where to send the donor after successful subscription and cancel
if (!defined('PAYPAL_RETURN_URL')) define('PAYPAL_RETURN_URL', BASE_PATH . 'thank-you');
if (!defined('PAYPAL_CANCEL_URL')) define('PAYPAL_CANCEL_URL', BASE_PATH . 'partners');
// Hosted donation button id for one-time PayPal donations
if (!defined('PAYPAL_HOSTED_BUTTON_ID')) define('PAYPAL_HOSTED_BUTTON_ID', '');
// Toggle sandbox for IPN validation and testing (false for live)
if (!defined('PAYPAL_USE_SANDBOX')) define('PAYPAL_USE_SANDBOX', false);

// Newsletter configuration
// Enable double opt-in for production; users must confirm via email
if (!defined('NEWSLETTER_DOUBLE_OPT_IN')) define('NEWSLETTER_DOUBLE_OPT_IN', true);
// Confirmation token expiry in days
if (!defined('NEWSLETTER_CONFIRM_EXPIRES_DAYS')) define('NEWSLETTER_CONFIRM_EXPIRES_DAYS', 7);

// Email queue defaults (overridable via includes/config.local.php generated in Admin Settings)
if (!defined('QUEUE_PAUSE_SENDING')) define('QUEUE_PAUSE_SENDING', false);
// Per-type max attempts (fallback to 5)
if (!defined('QUEUE_MAX_ATTEMPTS_NEWSLETTER')) define('QUEUE_MAX_ATTEMPTS_NEWSLETTER', 5);
if (!defined('QUEUE_MAX_ATTEMPTS_NEWSLETTER_TEST')) define('QUEUE_MAX_ATTEMPTS_NEWSLETTER_TEST', 5);
if (!defined('QUEUE_MAX_ATTEMPTS_CONTACT')) define('QUEUE_MAX_ATTEMPTS_CONTACT', 5);
